// docs/src/examples/dropdown/dropdown-solid.jsx
import { useAutoAnimate } from "@formkit/auto-animate/solid"
import { createSignal, Show } from "solid-js"

const Dropdown = () => {

  const [show, setShow] = createSignal(false)
  const reveal = () => setShow(!show)

  let parent

  useAutoAnimate(() => parent /* optional config */)

  return <div ref={parent}>
    <strong className="dropdown-label" onClick={reveal}>Click me to open!</strong>
    <Show when={show()} keyed>
      <p className="dropdown-content">Lorum ipsum...</p>
    </Show>
  </div>
}

export default Dropdown

// docs/src/examples/dropdown/dropdown.jsx
import { useState, useRef, useEffect } from 'react'
import autoAnimate from '@formkit/auto-animate'

const Dropdown = () => {
  const [show, setShow] = useState(false)
  const parent = useRef(null)

  useEffect(() => {
    parent.current && autoAnimate(parent.current)
  }, [parent])

  const reveal = () => setShow(!show)

  return <div ref={parent}>
    <strong className="dropdown-label" onClick={reveal}>Click me to open!</strong>
    { show && <p className="dropdown-content" >Lorum ipsum...</p> }
  </div>
}

export default Dropdown
