// docs/src/examples/disable/disable.vue
<script setup>
import { ref } from "vue"
import { useAutoAnimate } from "../../../../src/vue"

const balls = ref(["red", "green", "blue"])
const [parent, enable] = useAutoAnimate({ duration: 500 })

let isEnabled = ref(true)
function toggle() {
  isEnabled.value ? enable(false) : enable(true)
  isEnabled.value = !isEnabled.value
}
setInterval(() => {
  balls.value.push(balls.value.shift()!)
}, 600)
</script>

<template>
  <ul class="balls" ref="parent">
    <li v-for="color in balls" :key="color" :class="color">
      {{ color }}
    </li>
  </ul>
  <button @click="toggle" class="button button--alt">
    {{ isEnabled ? "🚫 Disable" : "✅ Enable" }} animations
  </button>
</template>

// docs/src/examples/disable/disable.jsx
import { useEffect, useState } from 'react'
import { useAutoAnimate } from '@formkit/auto-animate/react'

function Juggle() {
  const [balls, setBalls] = useState(['red', 'green', 'blue'])
  const [isEnabled, setIsEnabled] = useState(true)
  const [parent, enable] = useAutoAnimate({ duration: 500 })
  function toggle () {
    enable(!isEnabled)
    setIsEnabled(!isEnabled)
  }
  useEffect(() => {
    setTimeout(() => {
      const juggled = [...balls]
      juggled.push(juggled.shift())
      setBalls(juggled)
    }, 600)
  }, [balls])
  return (
    <>
      <ul ref={parent} className="balls">
        { balls.map(color => <li key={color} className={color}>{ color }</li>) }
      </ul>
      <button onClick={toggle}>
        { isEnabled ? "🚫 Disable" : "✅ Enable" } animations
      </button>
    </>
  )
}

export default Juggle
